//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flightgear.Control.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_MAO_ESQUERDA {
            get {
                return ((int)(this["SERVO_MAO_ESQUERDA"]));
            }
            set {
                this["SERVO_MAO_ESQUERDA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_BRACO_ESQUERDO {
            get {
                return ((int)(this["SERVO_BRACO_ESQUERDO"]));
            }
            set {
                this["SERVO_BRACO_ESQUERDO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_OMBRO_ESQUERDO {
            get {
                return ((int)(this["SERVO_OMBRO_ESQUERDO"]));
            }
            set {
                this["SERVO_OMBRO_ESQUERDO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_MAO_DIREITA {
            get {
                return ((int)(this["SERVO_MAO_DIREITA"]));
            }
            set {
                this["SERVO_MAO_DIREITA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_BRACO_DIREITO {
            get {
                return ((int)(this["SERVO_BRACO_DIREITO"]));
            }
            set {
                this["SERVO_BRACO_DIREITO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_OMBRO_DIREITO {
            get {
                return ((int)(this["SERVO_OMBRO_DIREITO"]));
            }
            set {
                this["SERVO_OMBRO_DIREITO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_QUADRIL_ESQUERDO {
            get {
                return ((int)(this["SERVO_QUADRIL_ESQUERDO"]));
            }
            set {
                this["SERVO_QUADRIL_ESQUERDO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_JOELHO_1_ESQUERDO {
            get {
                return ((int)(this["SERVO_JOELHO_1_ESQUERDO"]));
            }
            set {
                this["SERVO_JOELHO_1_ESQUERDO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_JOELHO_2_ESQUERDO {
            get {
                return ((int)(this["SERVO_JOELHO_2_ESQUERDO"]));
            }
            set {
                this["SERVO_JOELHO_2_ESQUERDO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_TORNOZELO_ESQUERDO {
            get {
                return ((int)(this["SERVO_TORNOZELO_ESQUERDO"]));
            }
            set {
                this["SERVO_TORNOZELO_ESQUERDO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_PE_ESQUERDO {
            get {
                return ((int)(this["SERVO_PE_ESQUERDO"]));
            }
            set {
                this["SERVO_PE_ESQUERDO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_QUADRIL_DIREITO {
            get {
                return ((int)(this["SERVO_QUADRIL_DIREITO"]));
            }
            set {
                this["SERVO_QUADRIL_DIREITO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_JOELHO_1_DIREITO {
            get {
                return ((int)(this["SERVO_JOELHO_1_DIREITO"]));
            }
            set {
                this["SERVO_JOELHO_1_DIREITO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_JOELHO_2_DIREITO {
            get {
                return ((int)(this["SERVO_JOELHO_2_DIREITO"]));
            }
            set {
                this["SERVO_JOELHO_2_DIREITO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_TORNOZELO_DIREITO {
            get {
                return ((int)(this["SERVO_TORNOZELO_DIREITO"]));
            }
            set {
                this["SERVO_TORNOZELO_DIREITO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SERVO_PE_DIREITO {
            get {
                return ((int)(this["SERVO_PE_DIREITO"]));
            }
            set {
                this["SERVO_PE_DIREITO"] = value;
            }
        }
    }
}
